[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1028:Enum Storage should be Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1031:Do not catch general exception types")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1032:Implement standard exception constructors")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1034:Nested types should not be visible")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1051:Do not declare visible instance fields")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming",        "CA1707:Identifiers should not contain underscores")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance",   "CA1819:Properties should not return arrays")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability",   "CA2007:Consider calling ConfigureAwait on the awaited task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style",         "IDE1006:Naming Styles")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage",         "CA2200:Rethrow to preserve stack details.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage",         "CA2234:Pass system uri objects instead of strings")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality",  "IDE0067:Dispose objects before losing scope",  Scope = "member", Target = "~M:Jannesen.PushNotification.Internal.APNSPushConnection.SendNotificationAsync(Jannesen.PushNotification.Notification)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1062:Validate arguments of public methods",  Scope = "member", Target = "~M:Jannesen.PushNotification.PushNotificationInvalidDeviceException.#ctor(Jannesen.PushNotification.Notification)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability",   "CA2000:Dispose objects before losing scope",   Scope = "member", Target = "~M:Jannesen.PushNotification.Internal.APNSPushConnection.SendNotificationAsync(Jannesen.PushNotification.Notification)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage",         "CA2213:Disposable fields should be disposed",  Scope = "member", Target = "~F:Jannesen.PushNotification.Internal.APNSPushConnection._connection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage",         "CA2213:Disposable fields should be disposed",  Scope = "member", Target = "~F:Jannesen.PushNotification.Internal.APNSPushConnection._connectionTimer")]
